"""Evidence-aware genomic research helpers."""

from .edit_assessment import EditAssessment, EditEvidence, ReviewTier, assess_edit
from .evidence import EvidenceLevel, permitted_wording
from .interactions import InteractionResult, rank_interactions
from .calibration import brier_score, expected_calibration_error
from .provenance import AssessmentRecord, StudyContext, create_record
from .predictors import Applicability, PredictionTask, PredictorOutput, integrate_outputs
from .species import (
    CYNOMOLGUS_MACAQUE_PROFILE,
    FRUIT_FLY_PROFILE,
    MOUSE_PROFILE,
    RAT_PROFILE,
    RHESUS_MACAQUE_PROFILE,
    ZEBRAFISH_PROFILE,
    SpeciesProfile,
    SpeciesValidation,
    validate_study_context,
)
from .snapshots import MGI_REPORTS, SnapshotManifest, create_mgi_snapshot
from .mgi import MgiAlleleEvidence, NormalizationSummary, normalize_phenotypic_alleles
from .impc import ImpcClient, ImpcGeneEvidence, ImpcGenePhenotype
from .benchmark import BenchmarkManifest, BenchmarkRecord, assign_gene_split, build_mgi_benchmark
from .baseline import BaselineReport, PhenotypePriorModel, RankingMetrics, evaluate_benchmark
from .impc_validation import (
    ImpcValidationManifest,
    ImpcValidationRecord,
    build_impc_validation,
)
from .impc_calibration import (
    BinaryCalibrationMetrics,
    ConstantSignificanceModel,
    ImpcCalibrationReport,
    evaluate_impc_calibration,
)
from .behive import (
    BEHIVE_EFFICIENCY_COMMIT,
    BEHIVE_EFFICIENCY_REFERENCE,
    BEHIVE_MOUSE_EDITORS,
    BehiveApplicability,
    BehiveEfficiencyPrediction,
    BehiveEfficiencyRequest,
    integrate_behive_efficiency,
    normalize_behive_efficiency,
)
from .behive_validation import (
    BehiveValidationMetrics,
    BehiveValidationReport,
    evaluate_behive_validation,
)
from .behive_bystander import (
    BEHIVE_BYSTANDER_COMMIT,
    BEHIVE_BYSTANDER_MOUSE_EDITORS,
    BEHIVE_BYSTANDER_REFERENCE,
    BehiveBystanderOutcome,
    BehiveBystanderPrediction,
    normalize_behive_bystander,
)
from .capabilities import (
    CapabilityStatus,
    PredictorCapability,
    capabilities_for_species,
    capability_matrix,
)
from .crispritz import (
    CRISPRITZ_COMMIT,
    CRISPRITZ_REFERENCE,
    CRISPRITZ_VERSION,
    CrispritzAuditReport,
    CrispritzDifferenceCount,
    CrispritzHit,
    import_crispritz_targets,
)
from .crisprscan import (
    CRISPRSCAN_COEFFICIENTS_SHA256,
    CRISPRSCAN_METHOD_REFERENCE,
    CRISPRSCORE_COMMIT,
    CRISPRSCORE_REFERENCE,
    CRISPRSCORE_VERSION,
    CrisprscanGuideScore,
    CrisprscanReport,
    score_crisprscan,
)
from .crisprscan_validation import (
    PREDICTION_FIELDS,
    CrisprscanTransferReport,
    evaluate_crisprscan_transfer,
)
from .dossier import (
    DOSSIER_SCHEMA_VERSION,
    DossierIntegrityResult,
    build_research_dossier,
    verify_dossier_integrity,
)
from .indelphi import (
    INDELPHI_COMMIT,
    INDELPHI_MODEL_ARTIFACT_FAMILY,
    INDELPHI_REFERENCE,
    INDELPHI_REPOSITORY,
    IndelphiOutcome,
    IndelphiPrediction,
    normalize_indelphi,
)
from .indelphi_validation import (
    INDELPHI_MOUSE_SUPPLEMENT_SHA256,
    IndelphiMouseTransferEvidence,
    indelphi_mouse_transfer_evidence,
)
from .housden import (
    HOUSDEN_CURRENT_RECOMMENDED_THRESHOLD,
    HOUSDEN_DEVELOPMENTAL_CONTEXT,
    HOUSDEN_EDIT_CLASS,
    HOUSDEN_GUIDE_EXPRESSION,
    HOUSDEN_HELP_URL,
    HOUSDEN_METHOD_REFERENCE,
    HOUSDEN_PREDICTOR,
    HOUSDEN_PUBLISHED_HIGH_EFFICIENCY_THRESHOLD,
    HOUSDEN_SERVICE_URL,
    HOUSDEN_SPECIES_PROFILE,
    HOUSDEN_TRAINING_DOMAIN,
    HousdenPrediction,
    normalize_housden,
)
from .fruit_fly_cas12a import (
    FRUIT_FLY_CAS12A_GENOTYPES_SHA256,
    FRUIT_FLY_CAS12A_GENOTYPES_URL,
    FRUIT_FLY_CAS12A_LIBRARY_SHA256,
    FRUIT_FLY_CAS12A_LIBRARY_URL,
    FRUIT_FLY_CAS12A_REFERENCE,
    FRUIT_FLY_CAS12A_SOURCE_DATA_SHA256,
    FRUIT_FLY_CAS12A_SOURCE_DATA_URL,
    PORT_2026_CAS12A_SOURCE,
    FruitFlyCas12aArrayEvidence,
    FruitFlyCas12aEvidenceAudit,
    FruitFlyCas12aSource,
    audit_fruit_fly_cas12a_evidence,
    lookup_fruit_fly_cas12a_array,
)
from .readiness import (
    EvidenceQualification,
    EvidenceUseStatus,
    SpeciesReadiness,
    readiness_for_species,
    readiness_matrix,
)
from .rat_validation import (
    RAT_ANDERSON_2018_SOURCE,
    RAT_TRANSFER_REFERENCE,
    RAT_TRANSFER_TABLE1_SHA256,
    RAT_TRANSFER_TABLE1_URL,
    RAT_TRANSFER_TABLE5_SHA256,
    RAT_TRANSFER_TABLE5_URL,
    RatGuideActivitySource,
    RatGuideTransferMetrics,
    RatGuideTransferReport,
    evaluate_rat_guide_transfer,
    prepare_rat_guide_transfer_template,
)

__all__ = [
    "AssessmentRecord",
    "Applicability",
    "BenchmarkManifest",
    "BenchmarkRecord",
    "BaselineReport",
    "BEHIVE_EFFICIENCY_COMMIT",
    "BEHIVE_EFFICIENCY_REFERENCE",
    "BEHIVE_MOUSE_EDITORS",
    "BEHIVE_BYSTANDER_COMMIT",
    "BEHIVE_BYSTANDER_MOUSE_EDITORS",
    "BEHIVE_BYSTANDER_REFERENCE",
    "BehiveBystanderOutcome",
    "BehiveBystanderPrediction",
    "BehiveApplicability",
    "BehiveEfficiencyPrediction",
    "BehiveEfficiencyRequest",
    "BehiveValidationMetrics",
    "BehiveValidationReport",
    "BinaryCalibrationMetrics",
    "ConstantSignificanceModel",
    "CYNOMOLGUS_MACAQUE_PROFILE",
    "CapabilityStatus",
    "CRISPRITZ_COMMIT",
    "CRISPRITZ_REFERENCE",
    "CRISPRITZ_VERSION",
    "CrispritzAuditReport",
    "CrispritzDifferenceCount",
    "CrispritzHit",
    "CRISPRSCAN_COEFFICIENTS_SHA256",
    "CRISPRSCAN_METHOD_REFERENCE",
    "CRISPRSCORE_COMMIT",
    "CRISPRSCORE_REFERENCE",
    "CRISPRSCORE_VERSION",
    "CrisprscanGuideScore",
    "CrisprscanReport",
    "CrisprscanTransferReport",
    "DOSSIER_SCHEMA_VERSION",
    "DossierIntegrityResult",
    "EditAssessment",
    "EditEvidence",
    "EvidenceQualification",
    "EvidenceLevel",
    "EvidenceUseStatus",
    "FRUIT_FLY_PROFILE",
    "FRUIT_FLY_CAS12A_GENOTYPES_SHA256",
    "FRUIT_FLY_CAS12A_GENOTYPES_URL",
    "FRUIT_FLY_CAS12A_LIBRARY_SHA256",
    "FRUIT_FLY_CAS12A_LIBRARY_URL",
    "FRUIT_FLY_CAS12A_REFERENCE",
    "FRUIT_FLY_CAS12A_SOURCE_DATA_SHA256",
    "FRUIT_FLY_CAS12A_SOURCE_DATA_URL",
    "FruitFlyCas12aArrayEvidence",
    "FruitFlyCas12aEvidenceAudit",
    "FruitFlyCas12aSource",
    "HOUSDEN_CURRENT_RECOMMENDED_THRESHOLD",
    "HOUSDEN_DEVELOPMENTAL_CONTEXT",
    "HOUSDEN_EDIT_CLASS",
    "HOUSDEN_GUIDE_EXPRESSION",
    "HOUSDEN_HELP_URL",
    "HOUSDEN_METHOD_REFERENCE",
    "HOUSDEN_PREDICTOR",
    "HOUSDEN_PUBLISHED_HIGH_EFFICIENCY_THRESHOLD",
    "HOUSDEN_SERVICE_URL",
    "HOUSDEN_SPECIES_PROFILE",
    "HOUSDEN_TRAINING_DOMAIN",
    "HousdenPrediction",
    "InteractionResult",
    "ImpcClient",
    "ImpcGeneEvidence",
    "ImpcGenePhenotype",
    "ImpcCalibrationReport",
    "ImpcValidationManifest",
    "ImpcValidationRecord",
    "INDELPHI_COMMIT",
    "INDELPHI_MODEL_ARTIFACT_FAMILY",
    "INDELPHI_MOUSE_SUPPLEMENT_SHA256",
    "INDELPHI_REFERENCE",
    "INDELPHI_REPOSITORY",
    "IndelphiMouseTransferEvidence",
    "IndelphiOutcome",
    "IndelphiPrediction",
    "MOUSE_PROFILE",
    "MGI_REPORTS",
    "MgiAlleleEvidence",
    "NormalizationSummary",
    "PredictionTask",
    "PREDICTION_FIELDS",
    "PORT_2026_CAS12A_SOURCE",
    "PredictorOutput",
    "PredictorCapability",
    "PhenotypePriorModel",
    "RankingMetrics",
    "RAT_PROFILE",
    "RAT_ANDERSON_2018_SOURCE",
    "RAT_TRANSFER_REFERENCE",
    "RAT_TRANSFER_TABLE1_SHA256",
    "RAT_TRANSFER_TABLE1_URL",
    "RAT_TRANSFER_TABLE5_SHA256",
    "RAT_TRANSFER_TABLE5_URL",
    "RatGuideActivitySource",
    "RatGuideTransferMetrics",
    "RatGuideTransferReport",
    "RHESUS_MACAQUE_PROFILE",
    "ReviewTier",
    "SpeciesProfile",
    "SpeciesValidation",
    "SpeciesReadiness",
    "SnapshotManifest",
    "StudyContext",
    "ZEBRAFISH_PROFILE",
    "assess_edit",
    "audit_fruit_fly_cas12a_evidence",
    "assign_gene_split",
    "brier_score",
    "build_mgi_benchmark",
    "build_impc_validation",
    "build_research_dossier",
    "capabilities_for_species",
    "capability_matrix",
    "create_record",
    "create_mgi_snapshot",
    "expected_calibration_error",
    "evaluate_benchmark",
    "evaluate_behive_validation",
    "evaluate_impc_calibration",
    "evaluate_crisprscan_transfer",
    "evaluate_rat_guide_transfer",
    "integrate_outputs",
    "integrate_behive_efficiency",
    "indelphi_mouse_transfer_evidence",
    "import_crispritz_targets",
    "normalize_phenotypic_alleles",
    "normalize_behive_efficiency",
    "normalize_behive_bystander",
    "normalize_housden",
    "normalize_indelphi",
    "lookup_fruit_fly_cas12a_array",
    "permitted_wording",
    "prepare_rat_guide_transfer_template",
    "rank_interactions",
    "readiness_for_species",
    "readiness_matrix",
    "score_crisprscan",
    "validate_study_context",
    "verify_dossier_integrity",
]
